repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0 # python 3.8+
    hooks:
      - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        language: system
        args: ["--config-file=pyproject.toml", "--install-types", "--non-interactive"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7 # python 3.8+
    hooks:
      - id: bandit
        language: python
        entry: bandit -r src/ -x tests/
        pass_filenames: false
