[project]
name = "azure-functions-openapi"
description = "OpenAPI (Swagger) integration for Python-based Azure Functions"
authors = [{ name = "Yeongseon Choe", email = "yeongseon.choe@gmail.com" }]
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
    "ruff",
    "mypy",
    "bandit",
    "pre-commit",
    "hatch",
    "git-changelog",
    "types-PyYAML"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/azure_functions_openapi/__init__.py"

[tool.bandit]
exclude_dirs = ["tests"]

[tool.mypy]
strict = true

[tool.mypy.yaml]
ignore_missing_imports = true
