name: Test and Coverage

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      # Create an isolated virtual environment so Makefile paths work
      - name: Create virtualenv and install dev dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install .[dev]

      - name: Show workspace contents (debug)
        run: ls -R

      - name: Run tests with coverage (Makefile)
        run: |
          . .venv/bin/activate
          make coverage

      - name: Verify coverage output
        run: ls -lh coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          slug: yeongseon/azure-functions-openapi
          verbose: true

