name: Test and Coverage

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]

      - name: List workspace contents
        run: ls -R

      - name: Run tests with coverage (Makefile)
        run: make coverage

      - name: Check if coverage.xml exists
        run: ls -lh coverage.xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
