name: Test and Coverage

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install .[dev]

      - name: Run pytest with coverage
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          pytest --cov=src/azure_functions_openapi --cov-report=xml

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
